config/routes.rb
Rails.application.routes.draw do
  root 'items#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  # get '/auth/:provider/callback', to: 'sessions#fb_login' 
  get '/auth/facebook/callback', to: 'sessions#fb_login' 
  # post '/signup', to: 'users#new'
  # get 'account', to: 'users#show'
  resources :users do
    resources :items, only: [:index, :new, :destroy, :edit]
  end

  resources :items, only: [:show, :update, :create, :new] do
    resources :bids, only: [:create]
  end

  # get '/items/new', to: 'items#new'
  # resources :items, only: [:show, :update, :destroy, :create, :new]
  # resources :users, :bids

  # get "/fonts/poppins/:font", to: "sessions#fonts"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :purchases, class_name: 'Item', foreign_key:  'buyer_id'
  has_many :sales, class_name: 'Item', foreign_key:  'seller_id'

  has_many :bids
  has_many :items, through: :bids

  has_secure_password #validations: false #suppress default validations

  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true#, length: { minimum: 6 }

  def field_error attrbt
    self.errors.[](attrbt).[](0)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'sessions_layout', only:[:new, :edit]
  before_action :logged_in_user, only: [:show, :edit]
  before_action :current_user, only: %i[show edit update destroy]

  

  
  def show
  end

  
  def new
    @user = User.new
  end

  
  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to current_user, notice: 'User was successfully created.'
    else
      render :new, layout: 'sessions_layout'
    end
  end

  
  def update
    if @current_user.update user_params
      redirect_to current_user, notice: 'Your acount was updated successfully'
    else
      render :edit, layout: 'sessions_layout'
    end
  end

  
  def destroy
    # binding.pry
    @current_user.destroy
    log_out
    redirect_to :root
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

# thin start --ssl --ssl-key-file=host.key --ssl-cert-file=host.cert

app/views/users/_form.html.erb
<section class="<%= action_class action%>">
  <div class="container">
    <div class="<%= action_class action%>-content">
      <div class="<%= action_class action%>-form">
        <h2 class="form-title"><%= action_title action %></h2>
        <%= sign_up_in_or_update user, action  %>
      </div>
      <div class="<%= action_class action%>-image">
        <figure><%= image_tag "#{action_class action}-image.jpg", alt: "sing up image" %></figure>
        <%= action_link action %>
      </div>
    </div>
    <%= link_to 'Back', '/' %>
  </div>
</section>

app/views/users/_purchase.html.erb
<tr>
  <%# <th scope="row">1</th> %>
  <td><%= purchase.title %></td>
  <td><%= purchase.seller.name %></td> 
  <td><%= purchase.end_time %></td>
</tr>

app/views/users/_sale.html.erb
<tr>
  <td><%= sale.title %></td>
  <td>$<%= sale.starting_price %></td> 
  <td>$<%= sale.minimum_price %></td>
  <td><%= sale.start_time %></td>
  <td><%= sale.status.capitalize %></td>
  <td><%= link_to_if sale.pending?, 'Edit', edit_user_item_path(current_user, sale)  %></td>
</tr>

app/views/users/backup.html.erb
<section class="signup">
  <div class="container">
    <div class="signup-content">
      <div class="signup-form">
        <h2 class="form-title"><%= title %></h2>
        <%= form_with model: user, class: "register-form", id: "register-form" do |form| %>
          <%= labeled_field form, 'name', "zmdi zmdi-account material-icons-name", "Your Name" %>
          <%= labeled_field form, 'email', "zmdi zmdi-email", "Your Email" %>
          <%= labeled_field form, 'password', "zmdi zmdi-lock", "Your Password" %>
          <%= labeled_field form, 'password_cofirmation', "zmdi zmdi-lock-outline", "Confirm Password" %>
         <div class="form-group form-button">
            <%= form.submit id: "signup", class: "form-submit", value: "Register" %>
          </div>
        <% end %>
      </div>
      <div class="signup-image">
        <figure><%= image_tag "signup-image.jpg", alt: "sing up image" %></figure>
        <a href="/login" class="signup-image-link">I am already member</a>
      </div>
    </div>
  <%= link_to 'Back', '/' %>
  </div>
</section>



<section class="sign-in">
  <div class="container">
    <div class="signin-content">
      
      <div class="signin-form">
        <h2 class="form-title">Sign in</h2>
        <%= flash[:danger] %>
        <%= form_with model: @user, url: login_path, class: "register-form", id: "login-form" do |form| %>
          <%= labeled_field form, 'email', "zmdi zmdi-email", "Your Email" %>
          <%= labeled_field form, 'password', "zmdi zmdi-lock", "Your Password" %>
          <div class="form-group form-button">
            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in">
          </div>
        <% end %>
        <div class="social-login">
          <span class="social-label">Or login with</span>
          <ul class="socials">
            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="signin-image">
        <figure><%= image_tag "signin-image.jpg", alt: "sing up image" %></figure>
        <a href="/users/new" class="signup-image-link">Create an account</a>
      </div>
    </div>
    <%= link_to 'Back', '/' %>
  </div>
</section>

app/views/users/edit.html.erb
<%= render 'form', user: @current_user, action: 'Update' %>

app/views/users/new.html.erb
<%= render 'form', user: @user, action: 'Sign up' %>

app/views/users/show.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Name:</strong>
    <%= @current_user.name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @current_user.email %>
  </p>
  <%= link_to 'Back', '/' %> |
  <%= link_to 'Edit', ['edit', @current_user] %>  <hr>
  Create new item <%= link_to 'here', new_user_item_path(@current_user) %> or <br>
  Manage your existing items  <%= link_to 'here', user_items_path(@current_user) %><hr>
  <%= button_to "Delete Youre Account", @current_user, method: :delete, controller: :users,
                                  data: { confirm: "You sure?" }, class:"btn btn-link" %>
</div>