config/routes.rb
Rails.application.routes.draw do
  root 'items#home'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  # get '/auth/:provider/callback', to: 'sessions#fb_login' 
  get '/auth/facebook/callback', to: 'sessions#fb_login' 
  # post '/signup', to: 'users#new'
  # get 'account', to: 'users#show'
  resources :users do
    resources :items, only: [:index, :new, :destroy, :edit]
  end

  resources :items, only: [:show, :update, :create, :new] do
    resources :bids, only: [:create]
  end

  # get '/items/new', to: 'items#new'
  # resources :items, only: [:show, :update, :destroy, :create, :new]
  # resources :users, :bids

  # get "/fonts/poppins/:font", to: "sessions#fonts"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  extend ItemsHelper::ClassHelper
  include ItemsHelper::InstanceHelper
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true # buyer_id won't be set
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'               # until someone buyes the item
                                                                                 # hence optional: true
  has_many :bids
  has_many :users, through: :bids
  has_many :item_details, dependent: :destroy
  has_many :images, through: :item_details
  has_many :bulletings, through: :item_details

  accepts_nested_attributes_for :images, reject_if: proc {|attributes| attributes[:path].blank?}, allow_destroy: true
  accepts_nested_attributes_for :bulletings, reject_if: proc {|attributes| attributes[:bulleting].blank?}, allow_destroy: true
  accepts_nested_attributes_for :bids

  validates_presence_of :title, :start_time, :end_time
  validates :status, inclusion: { in: %w(pending active sold failed), message: "%{attribute} is not a valid status" }
  validate :start_time_must_be_in_futur, on: :create
  validate :end_time_later_than_start_time, on: :create

  scope :filter_by_status, -> (status) { where status: status }

  def start_time_must_be_in_futur
    if start_time && (Item.dezone(start_time) < Item.dezone(Time.now))
      errors.add(:start_time,
                 'must be in the future!')
    end
  end

  def end_time_later_than_start_time
    errors.add(:end_time, 'must be ahead of start time!') if start_time && end_time && (start_time > end_time)
  end

  def instanciate_nested_attributes
    5.times do 
      self.images << Image.new
      self.bulletings << Bulleting.new
    end 
  end

  def set_sold
    self.images.clear
    self.images << Image.find_or_create_by(path: 'sold.jpg')
    self.buyer_id = Bid.last.user_id
  end

  def update_status
    if active?
      self.update status: 'active'
    elsif sold?
      set_sold
      self.update status: 'sold'
    elsif failed?
      self.update status: 'failed'
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, except: [:home]
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  before_action :all_items, only: [:home, :destroy]
  before_action :verify_owner, only: [:edit, :destroy]
  layout 'item_layout', only: [:show]

  def index
    @purchases = current_user.purchases
  end

  def home
    if params[:status] && !params[:status].empty?
      @items = Item.filter_by_status(params[:status])
    end
  end

  def new
    @item = Item.new
    @item.instanciate_nested_attributes
  end

  def show
  end

  def edit
  end

  def update
    if @item.update item_params
      redirect_to user_items_path(current_user), notice: 'Item was updated successfully.'
    else
      render :edit
    end
  end

  def create
    @item = Item.new item_params
    if @item.valid?
      images = images_params['images_attributes']
      upload_images @item, images
      @item.save
      redirect_to user_items_path(current_user), notice: 'Your item was added successfully.'
    else
      @item.instanciate_nested_attributes
      render :new 
    end
  end

  def destroy 
    @item.destroy
    redirect_to user_items_path(current_user)
  end

  private

  def find_item
    @item = Item.find_by id: params[:id]
  end

  def all_items
    @items  = Item.all
  end

  def item_params
    params.require(:item).permit(:title, :seller_id, :start_time, :end_time, :starting_price, :minimum_price, :status,
                                 bulletings_attributes: {})
  end

  def verify_owner
    unless Item.find_by(id: params[:id]).seller == current_user
      render file: "#{Rails.root}/public/404.html",
             layout: false
    end
  end

  def images_params
    params.require(:item).permit(images_attributes: {})
  end

  def upload_images(item, images)
    if images
      images.each do |_, image|
        uploaded_file = image[:path]
        File.open(Rails.root.join('app', 'assets', 'images', uploaded_file.original_filename), 'wb') do |file|
          file.write(uploaded_file.read)
        end
        item.images << Image.create(path: uploaded_file.original_filename)
      end
    else
      item.images << Image.find_or_create_by(path: 'no_image.jpg')
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper 
  module InstanceHelper
    include ActionView::Helpers::TagHelper
    # include ActionView::Helpers::FormHelper
    # include ActionView::Context
    # include ActionController
    # include Rails.application.routes.url_helpers
    
    def started?
      Item.dezone(Time.now) >= Item.dezone(start_time)
    end

    def ended?
      Item.dezone(Time.now) >= Item.dezone(end_time)
    end
    
    def sold?
      ended? && current_price >= minimum_price
    end

    def failed?
      ended? && current_price < minimum_price
    end
    
    def active?
      started? && !ended?
    end

    def pending?
      !started?
    end

    def owned_by? current_user
      seller == current_user
    end

    def display_as_sold 
      tag.li("Status: #{status}", class: 'list-group-item' ) <<
      tag.li("Listed by: #{seller.name}", class: 'list-group-item' ) <<
      tag.li("Auction started at: #{start_time}", class: 'list-group-item', class: 'list-group-item') << 
      tag.li("Auction ended at: #{end_time}", class: 'list-group-item') << 
      tag.li("Item bought by: #{buyer.name}", class: 'list-group-item')<< 
      tag.li("Item sold for: $#{current_price + starting_price}", class: 'list-group-item') 
    end
    
    def display_as_active
      tag.li("Status: #{status}", class: 'list-group-item' ) <<
      tag.li("Listed by: #{seller.name}", class: 'list-group-item' ) <<
      tag.li("Auction started at: #{start_time}", class: 'list-group-item')  <<
      tag.li("Auction ends at: #{end_time}", class: 'list-group-item')  <<
      tag.li("Starting price: $#{starting_price}", class: 'list-group-item') <<
      # tag.li("Shipping: $#{shipping}", class: 'list-group-item') <<
      tag.li("Current price: $#{starting_price + current_price}", class: 'list-group-item') 
      # form_with(model: Bid.new, url: item_bids_path(@item), controller: :bid, action: :create) do |f|
      #   # f.hidden_field(:item_id, value: self.id) <<
      #   f.number_field( :amount ) <<
      #   f.submit('Place your bid')
      # end
    end

    def display_as_failed
      tag.li("Status: #{status}", class: 'list-group-item' ) <<
      tag.li("Listed by: #{seller.name}", class: 'list-group-item' ) <<
      tag.li("Auction started at: #{start_time}", class: 'list-group-item')  <<
      tag.li("Auction ended at: #{end_time}", class: 'list-group-item')  <<
      tag.li("Starting price: $#{starting_price}", class: 'list-group-item') <<
      tag.li("Shipping: $#{shipping}", class: 'list-group-item')
    end

    def display_as_pending
      tag.li("Status: #{status}", class: 'list-group-item' ) <<
      tag.li("Listed by: #{seller.name}", class: 'list-group-item' ) <<
      tag.li("Auction starts at: #{start_time}", class: 'list-group-item')  <<
      tag.li("Auction ends at: #{end_time}", class: 'list-group-item')  <<
      tag.li("Starting price: $#{starting_price}", class: 'list-group-item') <<
      tag.li("Shipping: $#{shipping}", class: 'list-group-item')
    end

    def status_based_display 
      update_status
      if sold?
        display_as_sold
      elsif active?
        display_as_active
      elsif failed?
        display_as_failed
      else
        display_as_pending
      end
    end
  end

  module ClassHelper
    # include ActionView::Helpers::TagHelper
    # include ActionView::Helpers::FormHelper
    # include Rails.application.routes.url_helpers

    def dezone(time)
      time.strftime('%Y-%m-%d %H:%M:%S')
    end
  end
end

app/views/items/_form.html.erb
<div class='container width-70'>
  <%= form_with model: @item do |f|   %>
    <%= f.hidden_field :seller_id, value: current_user.id%>
    <%= f.label :title %>
    <%= f.text_field :title %> <%= tag.small @item.errors&.[](:title)[0], class:"text-danger" %><br>
    <%= f.label :start_time %>
    <%= f.datetime_field :start_time %> <%= tag.small @item.errors&.[](:start_time)[0], class:"text-danger" %> <br>
    <%= f.label :end_time %>
    <%= f.datetime_field :end_time %> <%= tag.small @item.errors&.[](:end_time)[0], class:"text-danger" %><br>
    <%= f.label :starting_price %>
    $<%= f.number_field :starting_price, min: 0, step: 0.1 %> <%= tag.small @item.errors&.[](:starting_price)[0], class:"text-danger" %> <br>
    <%= f.label :minumum_price %>
    $<%= f.number_field :minimum_price, min: 0, step: 0.1 %> <%= tag.small @item.errors&.[](:minimum_price)[0], class:"text-danger" %><br>
    <%= f.label :shipping %>
    $<%= f.number_field :shipping, min: 0, step: 0.1 %> <%= tag.small @item.errors&.[](:shipping)[0], class:"text-danger" %> <br>
    <hr>
    <h5>Upload some images for your item:</h5>
    <br>
    <%= f.fields_for :images do |img| %>
      <%= img.file_field :path %><br>
    <% end %>
    <hr>
    <h5>List your item's features:</h5>
    <ul>
      <%= f.fields_for :bulletings do |blt| %>
        <li><%= blt.text_field :bulleting, style: "border-top-style: hidden;border-right-style: hidden;border-left-style: hidden;border-bottom-style: groove;background-color: #eee; outline: none; width: 70%" %><br>
        </li>
        <br>
      <% end %>
    </ul>
    <hr>
    <%= f.submit %><br>
    <hr>
    <hr>
  <% end %>
  </div>

app/views/items/edit.html.erb
<%= render 'form', user: @item %>

<%= button_to "Delete This Item", user_item_path(current_user, @item), method: :delete, controller: :items,
                                  data: { confirm: "You sure?" }, class:"btn btn-link d-inline-block" %>

app/views/items/home.html.erb
<div class="container col-10 ">
  <br>
   <div class="row ">
      <div class="card-columns",  >  
        <% @items.each do |item| %>
          <% unless item.owned_by? current_user%>
          <div class="card d-inline-block card-columns col-sm-3" style="width: 18rem;hight: 45rem;">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <% item.images.each do |image| %>
                  <div class="carousel-item  <%= "active" if image == item.images.first %> " >
                    <%= image_tag image.path || '/no_image.jpg', class:"d-block w-30 img-fluid", style:'height: 250px;width: 300px;object-fit: fill;'%>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="card-body ">
              <h5 class="card-title"></h5>
              <p class="card-text "><%= item.title%></p>
            </div>
            <ul class="list-group list-group-flush">
              <%  %>
              <%= item.status_based_display %>
            </ul>
            <div class="card-body">
              <%=link_to "view item", item_path(item), class: "card-link" %>
            </div>
          </div>
          <% end %>
        <% end %>
    </div>
  </div> 
</div>

app/views/items/index.html.erb
<br>
<br>
<br>
<div class="container col-9" >
<h3>Your purchased items</h3>
  <% unless current_user.purchases.empty?%>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Item</th>
          <th scope="col">Price</th>
          <th scope="col">Bought on</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'users/purchase', collection: current_user.purchases %>
      </tbody>
    </table>
  <% else %>
    <h5>You don't have any purchaces yet</h5>
  <% end %>
  <br>
  <hr><h3>Your listed items</h3> <hr>
  <h5 id='notice' class='text-success'><%= notice %></h5>
  <% unless current_user.sales.empty? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Item</th>
          <th scope="col">Starting price</th>
          <th scope="col">Minimum price</th>
          <th scope="col">Starts on</th>
          <th scope="col">Status</th>
          <th scope="col">Edit item</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'users/sale', collection: current_user.sales %>
      </tbody>
    </table>
    <%= link_to 'Add more items', new_user_item_path(current_user) %>
  <% else %>
    <h5>You don't have any listed items yet</h5>
    <%= link_to 'Add items', new_user_item_path(current_user) %>
  <% end %>
</div>

app/views/items/new.html.erb
<%= render 'form', user: @item %>

app/views/items/show.html copy.erb
    <div>
      <div class="slideshow-container">
        <div class="mySlides fade">
          <div class="numbertext">1 / 3</div>
          <%= image_tag "item1_1.jpg", style:"width:30%; height:30%" %>
          <div class="text">Caption Text</div>
        </div>
        <div class="mySlides fade">
          <div class="numbertext">2 / 3</div>
          <%= image_tag "i2im1.jpg", style:"width:30%; height:30%" %>
          <div class="text">Caption Two</div>
        </div>
        <div class="mySlides fade">
          <div class="numbertext">3 / 3</div>
          <%= image_tag "item1_3.jpg", style:"width:30%; height:30%" %>
          <div class="text">Caption Three</div>
        </div>
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br>
      <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
      </div>
    </div>

app/views/items/show.html.erb
<div style='text-align: center;'>
  <div class="slideshow-container">
    <% @item.images.each do |img|%>
      <div class="mySlides fade">
        <div class="numbertext">1 / 3</div>
        <%= image_tag img.path, style:"width:450px; height:400px" %>
        <div class="text"></div>
      </div>
    <% end %>
    <a class="prev" onclick="plusSlides(-1)" >&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <div class="d-flex text-center " style='text-align: center;'>
    <% @item.images.each.with_index(1) do |_, indx|%>
      <span class="dot" onclick="currentSlide(<%= indx %>)"></span>
    <% end %>
  </div>
  <hr>
  <div class="card-body ">
    <h5 class="card-title"></h5>
    <%= tag.h4 @item.title, class:"card-text " %>
  </div>
  <ul class="list-group list-group-flush" style="list-style-type:none;">
    <li class="list-group-item"> <%= @item.status_based_display   %> </li>
  </ul>
  <% if @item.active? %>
    <%= form_with model: Bid.new, url: item_bids_path(@item) do |f| %>
      <%= f.number_field :amount, min: 0, step: 0.5, name: 'amount' %>
      <div><small id='alert' style='color: red'><%= alert %></small></div>
      <%= f.submit('Place your bid') %>
    <% end %>
  <% end %>
</div>
<%= tag.hr %>
<%= tag.hr %>
<%= tag.h2 'Item detail:' %>
<ul class="list-group">
  <% unless @item.bulletings.empty? %>
    <% @item.bulletings.each do |bullet|%>
      <%= tag.li bullet.bulleting, class:"list-group-item"%><br>
    <% end %>
  <% else %>
    <h3> No extra details available at the moment!</h3>
  <% end %>
</ul>